version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${DATABASE_NAME}
      - ME_CONFIG_BASICAUTH_USERNAME=appota123
      - ME_CONFIG_BASICAUTH_PASSWORD=appota123
    depends_on:
      - mongo
    ports:
      - "8888:8081"
